name: Prettier Check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          # This part is also where you can pass other options, for example:
          working_directory: /frontend
          prettier_options: --write **/*.{js,md}

# on: 
#   pull_request:
#     branches:
#       - main
# jobs:
#   prettier-frontend:
#     runs-on: ubuntu-latest
#     name: Format Prettier on Frontend
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3
#       - name: Set up Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: '18'
#       - name: Install dependencies
#         run: |
#           cd "frontend"
#           npm install
#       - name: Run Prettier
#         run: |
#           cd "frontend"
#           npm run format:fix
  # prettier-backend:
  #   runs-on: ubuntu-latest
  #   name: Format Prettier on Backend
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #     - name: Set up Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: '18'
  #     - name: Install dependencies
  #       run: |
  #         cd "backend"
  #         npm install
  #     - name: Run Prettier
  #       run: |
  #         cd "backend"
  #         npm run format:fix
