name: Prettier Check

on: [push]

jobs:
  prettier-frontend:
    runs-on: ubuntu-latest
    name: Format Prettier on Frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          cd "frontend"
          npm install
      - name: Run Prettier
        run: |
          cd "frontend"
          npm run format:fix
  prettier-backend:
    runs-on: ubuntu-latest
    name: Format Prettier on Backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List backend directory contents
        run: |
          ls -la backend
      - name: Install dependencies
        run: |
          cd "backend"
          npm install
      - name: Run Prettier
        run: |
          cd "backend"
          npm run format:fix
