name: Prettier Check

on: [push]

jobs:
  prettier-frontend:
    runs-on: ubuntu-latest
    name: Check Prettier on Frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run:
          cd "frontend"
          npm install
      - name: Run Prettier
        run:
          cd "frontend"
          npm run format